#!/bin/sh

# This script starts the build process on post-receieve git hook.
# The $GIT_DIR is set by Git before executing the hook.

function log() {
  echo "$(date -u +%Y-%m-%d_%TZ) git-ci: $1"
}

if [ -z $GIT_DIR ]; then
  log "error: \$GIT_DIR is not set"
  log "this script should only be run as a git hook"
  exit 1
else
  ROOT="$GIT_DIR/.."
fi

function build {
  log "building..."
  START_TIME=`date +%s`
  make -C $ROOT build
  END_TIME=`date +%s`
  log "build finished, took $((END_TIME - START_TIME)) seconds"
  log "     < Your disgusting human food is ready, sir! >"
  log "=^~^= ´"
}

echo "=-=- Git CI =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "starting the build process..."
echo "waking up the ceiling kitten to fulfill your request..."
echo "     < Howdy, you hairless piece of human flesh! >"
echo "=^~^= ´"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="

# Setup logging.
TODAY=`date -u +"%Y-%m-%d"`
mkdir -p $ROOT/build/log
STDOUT_LOG="$ROOT/build/log/kardan-${TODAY}-stdout.log"
STDERR_LOG="$ROOT/build/log/kardan-${TODAY}-stderr.log"
exec 1>> $STDOUT_LOG
exec 2>> $STDERR_LOG

# Finnaly run the build function.
build &
